### ISSUE TITLE
Make temporal-sql-tool idempotent

### ISSUE THREAD

**Issue by tgaddair** [temporalio/temporal#1433] opened 2021-04-05 00:19 UTC
As part of my k8s deployment, I'd like to run a job to create/update the Temporal schema if it does not exist or is out of date.

```
temporal-sql-tool setup-schema -v 0.0
```

However, if the schema already exists, this command will raise an error:

```
2021/04/05 00:06:12 Starting schema setup, config=&{SchemaFilePath: InitialVersion:0.0 Overwrite:false DisableVersioning:false}
2021/04/05 00:06:12 Setting up version tables
2021/04/05 00:06:12 Error 1050: Table 'schema_version' already exists
```

It would be awesome if instead the CLI tool would exit gracefully if the table already exists.

**Comment by wxing1292** [comment] 2021-04-05 20:35
duplicate of #1087

**Comment by wxing1292** [comment] 2021-04-05 20:35
plz reference #1087 
close

**Closed by wxing1292** 2021-04-05 20:35 UTC
Labels: enhancement
