### ISSUE TITLE
Include last activity failure into timeout failure

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal#3304] opened 2022-09-02 18:00 UTC
**Is your feature request related to a problem? Please describe.**
When an activity keeps failing and then hits the ScheduleToClose timeout, only the ScheduleToClose timeout is included into the ActivityTaskFailed event. Here is an example:
```
    "activityTaskTimedOutEventAttributes": {
      "failure": {
        "message": "activity ScheduleToClose timeout",
        "source": "Server",
        "stackTrace": "",
        "cause": null,
        "timeoutFailureInfo": {
          "timeoutType": "ScheduleToClose",
          "lastHeartbeatDetails": null
        }
      },
```
This makes troubleshooting hard as the original cause for the timeout (activity failures) is lost.

**Describe the solution you'd like**
Include the last activity failure into the timeout failure as a cause.

**Comment by yiminc** [comment] 2022-09-02 21:38
consider change the failure into repeated field, like:
message ActivityTaskStartedEventAttributes {
    // The id of the `ACTIVITY_TASK_SCHEDULED` event this task corresponds to
    int64 scheduled_event_id = 1;
    // id of the worker that picked up this task
    string identity = 2;
    // TODO ??
    string request_id = 3;
    // Starting at 1, the number of times this task has been attempted
    int32 attempt = 4;
    // Will be set to the most recent failure details, if this task has previously failed and then
    // been retried.
    repeated temporal.api.failure.v1.Failure last_failure = 5;
}

**Comment by MichaelSnowden** [comment] 2022-09-07 00:08
I'm unable to reproduce this issue with the latest server. I made an example change to samples-go ([diff](https://github.com/temporalio/samples-go/compare/main...MichaelSnowden:samples-go:timeout_example)) to reproduce this, and the history event I saw contained the failure cause of the latest failed activity attempt:

```
{
    "eventId": "7",
    "eventTime": "2022-09-06T20:48:44.219781544Z",
    "eventType": "ActivityTaskTimedOut",
    "version": "0",
    "taskId": "1048645",
    "activityTaskTimedOutEventAttributes": {
      "failure": {
        "message": "activity ScheduleToClose timeout",
        "source": "Server",
        "stackTrace": "",
        "cause": {
          "message": "oops",
          "source": "GoSDK",
          "stackTrace": "",
          "cause": null,
          "applicationFailureInfo": {
            "type": "",
            "nonRetryable": false,
            "details": null
          }
        },
        "timeoutFailureInfo": {
          "timeoutType": "ScheduleToClose",
          "lastHeartbeatDetails": null
        }
      },
      "scheduledEventId": "5",
      "startedEventId": "6",
      "retryState": "NonRetryableFailure"
    }
  }
```

Maybe this was already fixed by another diff?

**Closed by MichaelSnowden** 2022-09-07 00:08 UTC
Labels: enhancement
