### ISSUE TITLE
Use Temporal with a Cassandra Astra Backend

### ISSUE THREAD

**Issue by clun** [temporalio/temporal#2419] opened 2022-01-25 22:26 UTC
## Expected Behavior
As the first database to use for the persistence with temporal was Cassandra i was wondering if we could use Astra as well to avoid installing any DB locally.

## Actual Behavior
I download the zip file containing the different certificates and unzipping them in `./dynamicconfig. I got a username and password. Looking at the different samples I set up the server with a `docker-compose` in the following way:

```yaml
temporal:
    container_name: temporal
    environment:
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development.yaml
      - DB=cassandra
      - SKIP_SCHEMA_SETUP=false
      - CASSANDRA_SEEDS=<myhost>-eu-west-1.db.astra.datastax.com
      - CASSANDRA_PORT=29042
      - CASSANDRA_USER=<my_user>
      - CASSANDRA_PASSWORD=<my_password>
      - CASSANDRA_TLS_ENABLED=true
      - CASSANDRA_CERT=/etc/temporal/config/dynamicconfig/cert
      - CASSANDRA_CERT_KEY=/etc/temporal/config/dynamicconfig/key
      - CASSANDRA_CA=/etc/temporal/config/dynamicconfig/ca.crt
      - CASSANDRA_REPLICATION_FACTOR=3
    image: temporalio/auto-setup:1.14.2
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
```

User and password are validated, port is correct but the validation does not pass:

```
+ temporal-cassandra-tool --ep <db>-db.astra.datastax.com validate-health
2022-01-25T22:19:27.930Z INFO Validating connection to cassandra cluster. {"logging-call-at": "cqlclient.go:112"}
2022/01/25 22:23:59 error: failed to connect to 63.35.186.217:29042 due to error: x509: cannot validate certificate for 63.35.186.217 because it doesn't contain any IP SANs
```

I do not see any extra file or hints I could provide to help this tool. Could you provide a sample file or spotting if I made something wrong ?

## Steps to Reproduce the Problem

  1. Create a DB in Astra and create both temporal and temporal_visibility keyspaces
  1. Download the securebundle unzip in folder dynamic config
  1. use the docker-compose file above

## Specifications

  - Version: `1.14.2`
  - Platform: Docker-compose (MAC)

**Comment by clun** [comment] 2022-01-26 22:12
It seems the `temporal-cassandra-tool` try to validate the `IP against the cert` 
whereas it should validate `the dns record against the cert`.

**Comment by alexshtin** [comment] 2022-02-03 01:16
Absolutely possible with env `SKIP_SCHEMA_SETUP`: https://github.com/temporalio/temporal/blob/master/docker/auto-setup.sh#L299

**Comment by vaclavbroz** [comment] 2022-02-25 20:58
Having the same issue and same root cause analysis. SKIP_SCHEMA_SETUP is maybe a workaround but still the defect should be fixed in the temporal-cassandra-tool and elsewhere if necessary.

**Comment by vaclavbroz** [comment] 2022-02-25 22:12
It's definitely a bug.

Here is a full workaround:

It is possible to use a TLS proxy, e.g. https://github.com/ghostunnel/ghostunnel that will listen to plain socket and proxy a TLS secured server. Ghostunnel is by the way also written in Go, so aka friendship. Ghosttunnel can be started in a simple container, etc...

Full procedure on my dev setup (Windows WSL2):

- Manually install Go 1.17
- Download Ghostunnel
- Make ghostnunel
- Launch ghost tunnel with following:

`ghostunnel client --listen 172.17.0.1:10350 --target temporaldb.cassandra.cosmos.azure.com:10350 --disable-authentication --unsafe-listen`

- In your configuration use 172.17.0.1 for CASSANDRA_SEEDS

Your docker host IP and your PaaS Cassandra URL may differ...

**Comment by robholland** [comment] 2022-07-27 11:49
Those environment variables `CASSANDRA_TLS_DISABLE_HOST_VERIFICATION` and `CASSANDRA_TLS_SERVER_NAME` should work fine when set on the auto-setup container as the `temporal-cassandra-tool` would see them in the environment. Please can you confirm that these are not having the desired effect?

**Comment by robholland** [comment] 2022-07-27 11:50
Put another way I'm not sure what you mean by "not supported out of the box".

**Comment by robholland** [comment] 2022-07-27 14:09
I have confirmed that this works to connect to Astra using our auto-setup docker container:

```
      - DB=cassandra
      - SKIP_DB_CREATE=true
      - CASSANDRA_SEEDS=xxxx.db.astra.datastax.com
      - CASSANDRA_TLS_SERVER_NAME=xxxx.db.astra.datastax.com
      - CASSANDRA_DISABLE_INITIAL_HOST_LOOKUP=true
      - CASSANDRA_PORT=29042
      - CASSANDRA_USER=xxxx
      - CASSANDRA_PASSWORD=xxxx
      - CASSANDRA_TLS_ENABLED=true
      - CASSANDRA_CERT_KEY=/etc/temporal/config/dynamicconfig/key
      - CASSANDRA_CERT=/etc/temporal/config/dynamicconfig/cert
      - CASSANDRA_CA=/etc/temporal/config/dynamicconfig/ca.crt
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-cass.yaml
```

The initial lookup must be skipped and the server name must be set (to the same value as seeds). This is due to the way Astra's certificates are generated without IP SANS versus Cassandra's host lookup process which stores only IP addresses. More details here: https://github.com/gocql/gocql/issues/1611.

I'm going to close this as there is a working solution and temporal-cassandra-tool and the auto-setup image are behaving as expected. Please re-open if I have missed something that we can fix or improve.

**Closed by robholland** 2022-07-27 14:09 UTC
Labels: potential-bug
