### ISSUE TITLE
temporal-sql-tool for MySQL doesn't create databases for v0.0.1

### ISSUE THREAD

**Issue by vishwa-trulioo** [temporalio/temporal#4378] opened 2023-05-19 21:23 UTC
## Expected Behavior
I was following the helm chart repo to create the Databases and schema for [MySQL-Aurora](https://github.com/temporalio/helm-charts/tree/v1.20.3#install-with-your-own-mysql) v8 backend.

The command to create the database when a database name is supplied doesn't work. i.e.
```
./temporal-sql-tool create-database -database temporal_visibility
```
But, if I just run the below command, it creates a database named `temporal`.

## Actual Behavior
Here is the out put of the command,
```
/temporal$ ./temporal-sql-tool create-database --database temporal_visibility
Incorrect Usage: flag provided but not defined: -database

NAME:
   temporal-sql-tool create-database - creates a database

USAGE:
   temporal-sql-tool create-database [command options] [arguments...]

OPTIONS:
   --defaultdb value  optional default db to connect to, this is not the db to be created
```

However, if I create the database by myself and then run remaining commands with the tool to create schemas, then it works.

## Steps to Reproduce the Problem

  1. Build the `temporal-sql-tool` using the instructions provided.
  1. Create MySQL database instance.
  1. Attempt to create the `temporal` and `temporal_visibility`
  2. When trying it out, it will produce the error show in actual behavior section.

## Specifications

  - Version: temporal version 1.20.3
  - Platform: Ubuntu with AWS Aurora-MySQL

**Comment by mindaugasrukas** [comment] 2023-05-19 23:39
Duplicate of https://github.com/temporalio/helm-charts/issues/364

**Closed by mindaugasrukas** 2023-05-19 23:39 UTC
Labels: potential-bug
