### ISSUE TITLE
How to select a workflow Execution by scheduling tasks

### ISSUE THREAD

**Issue by CarlosEssun** [temporalio/temporal#3281] opened 2022-08-30 09:17 UTC
## Expected Behavior
When a scheduled task corresponds to multiple activities, for high availability, multiple workflow Execute s are started, but I want to choose only one of the multiple workflows, and there are those parameters or methods that can achieve this function.

## Actual Behavior
A scheduled task will be sent to Each Workflow Execution

## Steps to Reproduce the Problem

  1.Taking the cron in the samples-go example as a test example, two workers are started and triggered every two minutes, and the workers on different nodes have received the task information.
 

## Specifications

  - Version: 1.16.2
  - Platform: docker-compose

**Comment by dnr** [comment] 2022-09-08 23:05
Hi, I'm having a little trouble figuring out what exactly you're asking. It might help to clarify a few things: you should think of a workflow execution as an abstract computation. It doesn't always happen on a single worker: the workflow execution is sliced into small computations called workflow tasks, and then those are assigned to workers as needed. Temporal already achieves high availability because of a particular worker fails, workflow tasks will be assigned to other workers. Even if a workflow task has been assigned and a worker dies, that task will get reassigned after a short timeout (10 seconds). So you don't need multiple workflow executions for high availability.

Are you asking for something like, eagerly sending workflow tasks (or activity tasks) to multiple workers and taking the first result, so you don't have to wait for the workflow task timeout?

**Comment by CarlosEssun** [comment] 2022-09-09 01:54
Thank you for your answer!
This is not the case, I just want to send to multiple workflows to get relevant information and execute tasks preemptively, not all workflows get this information and process.

**Comment by dnr** [comment] 2022-09-20 02:45
Ok, I'll mark this as a duplicate of #3309

**Closed by dnr** 2022-09-20 02:45 UTC
Labels: potential-bug
