### ISSUE TITLE
Resetting a workflow multiple times

### ISSUE THREAD

**Issue by antstorm** [temporalio/temporal#368] opened 2020-05-12 17:16 UTC
Hi 👋 

I ran into an issue with resetting workflows — it seems to be able to do it once, but every subsequent request (tried it with the same runID or the new runID) returns the runID of the 2nd execution and won't create another one.

Is this expected behaviour or a potential issue?

**Comment by vitarb** [comment] 2020-08-07 00:01
I'm unable to reproduce this issue, here is a set of steps that I've performed.
Setup: ran temporal server and hello-world worker from samples
```
> ~/projects/temporal (reset-with-corrupted-hist) $ ./tctl workflow run --tq hello-world --wt Workflow --et 60 -i '"temporal"'
Running execution:
  Workflow Id : dcf5da93-cc80-4126-a24c-1f89ede9c7da  
  Run Id      : 9a12d6a5-d768-4e87-8fe9-df6bd8ab51da  
  Type        : Workflow                              
  Namespace   : default                               
  Task Queue  : hello-world                           
  Args        : [temporal]                            
Progress:
2020/08/06 16:57:27 INFO  No logger configured for temporal client. Created default one.
  1, 2020-08-06T23:57:27Z, WorkflowExecutionStarted
  2, 2020-08-06T23:57:27Z, WorkflowTaskScheduled
  3, 2020-08-06T23:57:27Z, WorkflowTaskStarted
  4, 2020-08-06T23:57:27Z, WorkflowTaskCompleted
  5, 2020-08-06T23:57:27Z, ActivityTaskScheduled
  6, 2020-08-06T23:57:27Z, ActivityTaskStarted
  7, 2020-08-06T23:57:27Z, ActivityTaskCompleted
  8, 2020-08-06T23:57:27Z, WorkflowTaskScheduled
  9, 2020-08-06T23:57:27Z, WorkflowTaskStarted
  10, 2020-08-06T23:57:27Z, WorkflowTaskCompleted
  11, 2020-08-06T23:57:27Z, WorkflowExecutionCompleted

Result:
  Run Time: 1 seconds
  Status: COMPLETED
  Output: [Hello temporal!]
> ~/projects/temporal (reset-with-corrupted-hist) $ ./tctl wf reset --wid dcf5da93-cc80-4126-a24c-1f89ede9c7da --rid 9a12d6a5-d768-4e87-8fe9-df6bd8ab51da --reason "test" --event_id 4
{
  "runId": "fd8b5519-772a-4d5b-b8a4-a36f777f967a"
}
> ~/projects/temporal (reset-with-corrupted-hist) $ ./tctl wf reset --wid dcf5da93-cc80-4126-a24c-1f89ede9c7da --rid 9a12d6a5-d768-4e87-8fe9-df6bd8ab51da --reason "test" --event_id 4
{
  "runId": "bcf754e3-140d-430f-9eaf-59c14255bb2c"
}
> ~/projects/temporal (reset-with-corrupted-hist) $ ./tctl wf reset --wid dcf5da93-cc80-4126-a24c-1f89ede9c7da --rid 9a12d6a5-d768-4e87-8fe9-df6bd8ab51da --reason "test" --event_id 4
{
  "runId": "147f5539-31a6-4606-b912-aa451bcdaf92"
}
```

As you can see I'm getting a new run ID every time, no errors and everything looks normal to me.
I'm going to close this issue unless you have additional context that would help us reproduce it.

**Closed by vitarb** 2020-08-07 00:01 UTC
Labels: potential-bug
