### ISSUE TITLE
[Feature Request] SignalWithStart for external workflows

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/temporal#3773] opened 2022-10-17 18:00 UTC
Currently we have SignalWithStartWorkflow (Go SDK) via client api. 
Feature request is to add 
"SignalWithStartExternalWorkflow" (name tbd) which can be called in workflow code. Would behave same as SignalWithStartWorkflow.

**Comment by robholland** [comment] 2023-02-03 10:56
This is a duplicate of https://github.com/temporalio/temporal/issues/537

**Closed** 2023-02-03 10:56 UTC
Labels: enhancement
