### ISSUE TITLE
Custom Tags addition in existing Metric using java sdk is not working

### ISSUE THREAD

**Issue by techFool** [temporalio/temporal#695] opened 2020-08-27 04:16 UTC
Please refer to https://community.temporal.io/t/how-to-add-custom-tags-in-existing-temporal-metric-using-java-sdk/516 .

We are trying to add the custom tags but its not getting appeared in the metrics

**Comment by kkcmadhu** [comment] 2020-09-20 09:33
any idea when this can be fixed?

**Comment by vitarb** [comment] 2020-09-30 18:47
Closing as a duplicate of https://github.com/temporalio/sdk-java/issues/200
Please read correspondence provided there for more details.

**Closed by vitarb** 2020-09-30 18:47 UTC
