### ISSUE TITLE
CRON scheduled workflow with ContinueAsNew

### ISSUE THREAD

**Issue by benkelukas** [temporalio/temporal#3745] opened 2022-12-21 09:47 UTC
## Expected Behavior
Hi, I'm trying to use a CRON scheduled workflow together with the Continue-As-New feature.
When I trigger a CRON workflow, inside trigger Continue-As-New a few times, I expect it to schedule a new CRON run after the workflow is finished.

According to https://github.com/temporalio/temporal/issues/2146 this should work, but it does not for me.

## Actual Behavior
The workflow just ends and no new CRON run is scheduled

## Steps to Reproduce the Problem

  1. Clone https://github.com/benkelukas/temporal-cron-continue-as-new
  2. Run docker-compose build
  3. Run docker-compose up
  4. Run docker-compose exec app php app.php periodic:start
  5. Wait for 2 Continue-As-New triggers
  6. Observe Workflow being completed and no new CRON run scheduled

## Specifications

  - Version: 1.19.0
  - Platform: MacOS

**Comment by dnr** [comment] 2023-01-03 19:33
#2146 wasn't fixed, it was just marked as a dup. To be honest, this is unlikely to be fixed soon. You should try the new [Schedules](https://docs.temporal.io/workflows#schedule) feature instead.

**Comment by dnr** [comment] 2023-01-03 19:35
Duplicate of #746

**Closed** 2023-01-03 19:35 UTC
Labels: potential-bug

**Comment by benkelukas** [comment] 2023-01-17 09:35
Ah, alright, understood. Thanks for getting back to me and recommending a way forward! :)
