### ISSUE TITLE
Matching service unit tests are flaky

### ISSUE THREAD

**Issue by mastermanu** [temporalio/temporal#499] opened 2020-07-03 03:16 UTC
## Expected Behavior
Tests pass

## Actual Behavior
Sometimes tests randomly fail. I've seen this occur on local development environment and in Kite server. Getting it to reproduce is random, but once it reproduces, it fails pretty consistently until you reset the environment.

## Steps to Reproduce the Problem

See attached logs:
[temporal-server_build_1417_golang-unit-test.log](https://github.com/temporalio/temporal/files/4867572/temporal-server_build_1417_golang-unit-test.log)
## Specifications

  - Version:
  - Platform:

**Comment by alexshtin** [comment] 2020-07-14 19:23
Duplicate of #243.

**Closed** 2020-07-22 04:40 UTC
Labels: testing
