### ISSUE TITLE
Temporal Cassendra Failing issue in Kubernetes #3010

### ISSUE THREAD

**Issue by benji18son** [temporalio/temporal#3054] opened 2022-07-04 04:29 UTC
Hi Team,

Reported a issue in this below mentioned thread kindly please help us to resolve this issue.

https://community.temporal.io/t/temporal-cassendra-failing-issue-in-kubernetes/4891

@tsurdilo

**Comment by yiminc** [comment] 2023-08-27 19:47
duplicate of https://github.com/temporalio/temporal/issues/3010

**Closed by yiminc** 2023-08-27 19:47 UTC
Labels: potential-bug
