### ISSUE TITLE
Add control of archival feature initial state through docker-compose parameter

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/temporal#623] opened 2020-07-28 20:22 UTC
## Expected Behavior
As an admin i want to be able to control the initial state of archival feature through a docker-compose variable. Default should be set to disabled.

## Actual Behavior
There is no control via docker-compose config

**Comment by samarabbas** [comment] 2020-07-28 20:29
Duplicate of #595

**Closed by samarabbas** 2020-07-28 20:29 UTC
Labels: enhancement
