### ISSUE TITLE
Cron workflow with continue as new

### ISSUE THREAD

**Issue by eladman7** [temporalio/temporal#2146] opened 2021-11-07 16:02 UTC
Hi my name is Elad,
I׳m a backend engineer and working with Temporal for several months. I have come up with the following issue, hope you can assist me. 
## Expected Behavior
I execute a cron workflow with the temporal go sdk. This workflow creates many other child workflows so in order to reduce the history I started using continue as new after some configurable number of iterations from the parent workflow. The issue is that it seems like the continue as new parent workflows are not cron anymore. I would expect that they will keep the same option as the original executed workflow containing the CronSchedule option. 

## Actual Behavior
Continue as new solves the history limit problem but creates none scheduled workflows

## Steps to Reproduce the Problem

  1. create a cron scheduled workflow
  2. make it continue as new after some work/time
  3. notice the when all work is finished no workflow will be kept running for the next scheduled run as set in the CronSchedule

## Specifications

  - Version: 1.9.2 and web 1.9.0
  - Platform: Alpine Linux

Thank you,
Best Regards

**Comment by yiminc** [comment] 2021-11-07 16:40
@dnr please take a look. I suspect that when user code does continue as new, we lost the CronSchedule on the new run.

**Comment by dnr** [comment] 2021-11-09 03:01
Yes, this is a known issue: #148, #746. We might be able to fix it now that I split some of that code.

**Comment by yiminc** [comment] 2021-11-19 17:46
Duplicate of #746

**Closed by yiminc** 2021-11-19 17:46 UTC
Labels: bug, CRON
